export const meta = {
  name: "ProductCard",
  category: "data-display",
  description:
    "Tarjeta física de un producto financiero del usuario (BNPL o crédito), con tres estados (activo, congelado, bloqueado) y dos caras: la frontal (número y titular) y la trasera (saldo, progreso de uso y acciones).",
  figma: {
    library: "Aida",
    componentKey: "6a26bf3ba21c5c0880939bdbf69bad3a2267ce59",
    nodeId: "38:176",
    type: "component_set",
  },
  props: {
    product: ["bnpl", "credit"],
    state: ["active", "frozen", "blocked"],
    side: ["front", "back"],
    cardNumber: "string?",
    holderName: "string?",
    logo: "ReactNode?",
    statusIcon: "ReactNode?",
    balance: "string?",
    balanceCaption: "string?",
    progress: "number? (0 a 1)",
    primaryAction: "{ label: string; onClick?: () => void }?",
    secondaryAction: "{ label: string; onClick?: () => void }?",
  },
  tokens: [
    "card.bnpl.bg",
    "card.bnpl.bgSubtle",
    "card.bnpl.progressTrack",
    "card.bnpl.text",
    "card.credit.bg",
    "card.credit.bgSubtle",
    "card.credit.text",
    "card.frozen.bg",
    "card.frozen.text",
    "card.glow",
    "semantic.feedback.error",
    "semantic.brand.primary",
    "semantic.bg.surface",
    "sunflower.500",
    "radius.md",
    "radius.full",
    "fontSize.label-md",
    "fontSize.body-md",
    "fontSize.body-lg",
    "fontSize.display-xl",
    "fontSize.heading-lg",
    "lineHeight.label-md",
    "lineHeight.body-md",
    "lineHeight.body-lg",
    "lineHeight.display-xl",
    "fontFamily.base",
    "space.4",
    "space.8",
    "space.12",
    "space.16",
    "space.24",
    "fontWeight.light",
    "fontWeight.regular",
    "fontWeight.medium",
    "fontWeight.bold",
    "fontWeight.black",
  ],
  states: ["active", "frozen", "blocked"],
  useWhen:
    "Para mostrar un producto financiero del usuario (tarjeta de crédito o BNPL) como tarjeta: cara frontal en un carrusel o dashboard, cara trasera en el detalle con saldo y acciones. No usar para transacciones individuales — para eso, TransactionListItem.",
  a11y: {
    role: "group",
    keyboardSupport: true,
    notes:
      "El grupo lleva aria-label con producto, estado y cara. La barra de progreso es role='progressbar' con aria-valuenow. Los botones de la cara trasera son los de Button (teclado nativo); la cara frontal no es interactiva: si navega al detalle, envolver en un elemento con role='button'. Los efectos decorativos y el logo van con aria-hidden.",
  },
  dependencies: ["Button", "Icon"],
  notes:
    "Reconstruido en el Ciclo ARC 3 (2026-10-01, hallazgo 15) para coincidir con el component set real (38:176): 12 variantes (product × state × Side). Antes era un bloque de texto (title/subtitle/amount) que no existía en Figma: breaking change deliberado de la API. Decisiones: (1) las etiquetas de producto son las de Figma («Crédito», «BNPL»); (2) el estado decide el estilo de las acciones — active: principal + secundaria pequeñas en fila; frozen: principal deshabilitada; blocked: principal deshabilitada y terciaria, medianas y en columna —, y el consumidor pone las etiquetas («Congelar tarjeta», «Descongelar tarjeta», «Contactar soporte»); (3) statusIcon es un hueco para un Icon: el nodo status-badge de Figma contiene una elipse de 16 px llamada icon-placeholder, que solo se ve en blocked (en frozen se unificó en Figma el 2026-10-02 a «sin marcador» en las cuatro variantes; antes era un punto blanco, un aro gris o no existía). Por defecto se dibuja un `Icon lock` de 16 px en el color de error (2026-10-02, tarea pendiente del Ciclo ARC 3); si se pasa un statusIcon propio se muestra también en frozen; (4) los efectos decorativos (mancha difuminada, girada 180° como en Figma, y brillo) se dibujan en SVG sin el ruido de Figma (feTurbulence); el número de tarjeta mezcla estilos como en Figma (puntos Black 32, dígitos Light 24); (5) en active la pista es card/credit/text en crédito y card/bnpl/progress-track en BNPL (ambas blancas; la de BNPL se creó el 2026-10-02 para no usar un token de otro producto), y en frozen/blocked pista y relleno comparten color, así que la barra no distingue progreso (posible descuido de Figma); (6) el borde de card.border ya no se usa: Figma no tiene borde salvo en blocked (error, 2 px frontal y 1,5 px trasera).",
} as const;
